### ISSUE TITLE
Cloudstream V4.5.1 beta and stable - app crashes

### ISSUE THREAD

**Issue by aboodj87** [recloudstream/cloudstream#1570]
### Steps to reproduce

Works for 5 mins and keep exiting for no reason  and tried couple of versions all the same

### Expected behavior

Keeps crashing 

### Actual behavior

All versions keeps crashing for no reason

### Cloudstream version and commit hash

840274d

### Android version

Android 10

### Logcat

```java

```

### Acknowledgements

- [x] I am sure my issue is related to the app and **NOT some extension**.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [x] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Please try the latest per-release as the issue might have been fixed.

**Comment by aboodj87** [comment]
> Please try the latest per-release as the issue might have been fixed.

i still have same issue

**Comment by aboodj87** [comment]
> Hi everyone i have problem with cloudstream! It's shutdown every 20 or 30 min I'm running in Nvidia Shield Pro Box android tv thanks for helping me

There is no solution I've been waiting for a very long time and there is nothing yet if you not have any solution. Please provide it because i've been checking the website and there is still the same issue. No matter what solutions they've been saying, and it's something to do.
Still I have 20 mins app exiting by itself, no matter how much I troubleshoot
