### ISSUE TITLE
App backup doesn't work

### ISSUE THREAD

**Issue by astrocaat** [recloudstream/cloudstream#580]
### Steps to reproduce

1. Go to Settings.
2. Go to Updates and backup.
3. Click on Backup data.

### Expected behavior

A .json file should be created. 

### Actual behavior

On the previous pre-release, the app crashed. On the latest pre-release, it doesn't crash anymore but instead nothing happens and no backup file is created. 

### Cloudstream version and commit hash

4.1.8 - f018200

### Android version

Android 10 (TV)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
should be fixed as of ce1f48978be3aada3e6b68d8726539375c3f14f1

**Comment by astrocaat** [comment]
Just updated and still doesn't work. I'm getting an exception: "Error backing up Java.io.IOException: unable to create file".

**Comment by LagradOst** [comment]
@astrocaat might be fixed as of 6089cbc48493d746a110bba8d9997c3d2209b82e
